Adam.20240918.filter select
danielmtro/VFX_FPGA pull request #15
Opened 2024-09-24 08:51 UTC by AdamRiesel

Completing test benches to prepare for merge

2024-09-24 08:54 UTC, AdamRiesel commented
![inversion_filter_terminal_output](https://github.com/user-attachments/assets/5702c3e2-717d-4231-9fc3-b3297858ebd5)
![inversion_filter_waveform](https://github.com/user-attachments/assets/66bb54bc-5231-498a-a079-c8d166abacec)

Inversion filter: Testbenched

2024-09-24 08:55 UTC, AdamRiesel commented
![brightness_filter_terminal_output](https://github.com/user-attachments/assets/304008fb-9432-4e75-b94a-16132930ee1e)
![brightness_filter_waveform](https://github.com/user-attachments/assets/45248ed6-7a0f-4d37-b59b-eb2e1c3d3925)

brightness filter is testbenched

2024-09-25 01:58 UTC, AdamRiesel commented
![inversion_filter_terminal_output](https://github.com/user-attachments/assets/7a297ea5-7d82-436e-85d5-4602928bc150)

![inversion_filter_waveform](https://github.com/user-attachments/assets/2bb53ad1-152b-402a-9e86-14d6483456fe)
inversion filter testbenched

2024-09-25 01:58 UTC, AdamRiesel commented
![brightness_filter_waveform](https://github.com/user-attachments/assets/e8d0506b-d7f3-4009-ad6b-9f682d61ec8a)
![brightness_filter_terminal_output](https://github.com/user-attachments/assets/56a4c591-f9f2-4528-8211-9b6c78ebb25d)
brightness filter testbenched

2024-09-25 02:21 UTC, AdamRiesel commented
![filter_select_waveform](https://github.com/user-attachments/assets/d240a21d-a726-443b-bb12-66247a88f222)
![filter_select_terminal_output](https://github.com/user-attachments/assets/6498d7ca-de21-42ec-9823-ca5debabac06)
Filter select is testbenched for brightness and inversion

2024-09-25 02:34 UTC, AdamRiesel commented
![data_expander_waveform](https://github.com/user-attachments/assets/776f303c-10a2-4ed0-b133-07f91952937b)
data expander test bench

2024-09-25 02:38 UTC, AdamRiesel commented
Files to review:
filter select, brightness_filter, inversion_filter

2024-09-25 02:48 UTC, danielmtro requested changes

2024-09-25 02:48 UTC, danielmtro commented on src/filter_select.sv
> +		data_out = (inv_data | blur_data | bri_data | edge_data);
Didn't we agree to change this yesterday cos we can't edit the IP's functionality to make this possible?

2024-09-25 03:30 UTC, AdamRiesel commented on src/filter_select.sv
> +		data_out = (inv_data | blur_data | bri_data | edge_data);
you should have been looking in src/scale_filter_show/ but I changed this and the other ones in src/ anyway

2024-09-25 03:58 UTC, danielmtro approved these changes
LGTM

2024-09-25 07:02 UTC, merged