Developing a brightness filter
danielmtro/VFX_FPGA pull request #7
Opened 2024-09-12 23:59 UTC by AdamRiesel

Hopefully can use IPs

2024-09-13 05:09 UTC, AdamRiesel commented
![image](https://github.com/user-attachments/assets/eb176f25-93d7-4e28-a995-0fcb09534b91)

2024-09-13 05:11 UTC, AdamRiesel commented
Brightness filter is complete and testbenched. Note that the multiplication factor is freq_flag +1 so when `freq_flag = 2` we have 7*3 = 21 and so the output is 15 (1111)

2024-09-13 05:14 UTC, danielmtro requested changes
Some changes + resolve readme conflicts

2024-09-13 05:14 UTC, danielmtro commented on src/brightness_filter.sv
> +		blue_br 	= (blue > (MAX_VAL / (freq_flag + 1))) ? MAX_VAL : (freq_flag + 1) * blue;
Division operations very bad in verilog. 
They synthesis like cancer.

Is there a work around that we can do?

2024-09-13 05:14 UTC, danielmtro commented on src/brightness_filter.sv
> +		blue_br 	= (blue > (MAX_VAL / (freq_flag + 1))) ? MAX_VAL : (freq_flag + 1) * blue;
Can you check the logic element utilisation on compilation?

2024-09-13 09:36 UTC, AdamRiesel commented on src/brightness_filter.sv
> +		blue_br 	= (blue > (MAX_VAL / (freq_flag + 1))) ? MAX_VAL : (freq_flag + 1) * blue;
Ah shit, you're probably right.
I can rearrange terms to do multiplication instead

2024-09-18 07:50 UTC, danielmtro approved these changes
LGTM

2024-09-18 07:50 UTC, merged